"""photo + pedigree document upload

Revision ID: 7164b6e9dd2d
Revises: ebbec637b60a
Create Date: 2026-06-10 15:42:38.410968

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7164b6e9dd2d"
down_revision = "ebbec637b60a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='' — tabele mają już dane (seed), więc nowe kolumny NOT NULL
    # muszą mieć wartość domyślną dla istniejących wierszy (inaczej SQLite odrzuci ADD COLUMN).
    with op.batch_alter_table("animals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("photo_filename", sa.String(length=120), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("pedigree_document", sa.String(length=120), nullable=False, server_default="")
        )

    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("photo_filename", sa.String(length=120), nullable=False, server_default="")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.drop_column("photo_filename")

    with op.batch_alter_table("animals", schema=None) as batch_op:
        batch_op.drop_column("pedigree_document")
        batch_op.drop_column("photo_filename")

    # ### end Alembic commands ###
