"""init schema

Revision ID: ebbec637b60a
Revises:
Create Date: 2026-06-03 00:46:23.202949

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ebbec637b60a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_a_id", sa.Integer(), nullable=False),
        sa.Column("user_b_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_a_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_b_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a_id", "user_b_id", name="uq_conversation_pair"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_user_a_id"), ["user_a_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_user_b_id"), ["user_b_id"], unique=False)

    op.create_table(
        "farms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("species", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("voivodeship", sa.String(length=60), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("accent_color", sa.String(length=20), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("contact_phone", sa.String(length=40), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_farms_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_farms_species"), ["species"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_is_read"), ["is_read"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_recipient_id"), ["recipient_id"], unique=False
        )

    op.create_table(
        "animals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("species", sa.String(length=20), nullable=False),
        sa.Column("breed", sa.String(length=120), nullable=False),
        sa.Column("sex", sa.String(length=10), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("color", sa.String(length=80), nullable=False),
        sa.Column("registration_number", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("available_for_breeding", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("sire_id", sa.Integer(), nullable=True),
        sa.Column("dam_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dam_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sire_id"],
            ["animals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("animals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_animals_breed"), ["breed"], unique=False)
        batch_op.create_index(batch_op.f("ix_animals_dam_id"), ["dam_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_animals_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_animals_registration_number"), ["registration_number"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_animals_sire_id"), ["sire_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_animals_species"), ["species"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_messages_sender_id"), ["sender_id"], unique=False)

    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=True),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "((animal_id IS NOT NULL) + (farm_id IS NOT NULL)) = 1",
            name="ck_favorite_exactly_one_target",
        ),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "animal_id", name="uq_favorite_user_animal"),
        sa.UniqueConstraint("user_id", "farm_id", name="uq_favorite_user_farm"),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favorites_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_user_id"))

    op.drop_table("favorites")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_sender_id"))
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))

    op.drop_table("messages")
    with op.batch_alter_table("animals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_animals_species"))
        batch_op.drop_index(batch_op.f("ix_animals_sire_id"))
        batch_op.drop_index(batch_op.f("ix_animals_registration_number"))
        batch_op.drop_index(batch_op.f("ix_animals_farm_id"))
        batch_op.drop_index(batch_op.f("ix_animals_dam_id"))
        batch_op.drop_index(batch_op.f("ix_animals_breed"))

    op.drop_table("animals")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_recipient_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_read"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_farms_species"))
        batch_op.drop_index(batch_op.f("ix_farms_owner_id"))

    op.drop_table("farms")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_b_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_user_a_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
